Add Entity Slicing using Entity Manifests to Cedar
cedar-policy/cedar pull request #1105
Opened 2024-07-31 20:48 UTC by oflatt

## Description of changes

This PR allows users of Cedar to get an *entity slice* of an existing `Entities` store using the entity manifest.
Mainly this is useful for testing entity manifests. However, it may also be useful for users to load all entities in to memory, but only send a slice over the network to a server.

## Issue #, if available

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [ ] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).
- [ ] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).
- [ ] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [ ] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)
- [x] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).
- [ ] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [ ] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.
- [ ] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)
- [x] Requires updates, but I do not plan to make them in the near future. (Make sure that your changes are hidden behind a feature flag to mark them as experimental.)
- [ ] I'm not sure how my change impacts `cedar-spec`. (Post your PR anyways, and we'll discuss in the comments.)

2024-07-31 20:49 UTC, oflatt commented
This PR stacks on top of #1102 
It looks like I can't select that PR as a base branch since it's from my fork of Cedar.

2024-07-31 20:56 UTC, oflatt commented on cedar-testing/src/cedar_test_impl.rs
> +                    let entity_slice = entity_manifest
Are we allowed to panic in the testing infra here? We could return a new kind of TestResult or something like that.
Or perhaps I'm abusing the `is_authorized` function

2024-08-01 18:42 UTC, oflatt commented
Looks like changing the API for cedar testing broke downstream dependencies build

2024-08-28 02:55 UTC, oflatt commented on cedar-testing/src/cedar_test_impl.rs
> +                    let entity_slice = entity_manifest
Edit: Removed use of panic

2024-09-18 19:18 UTC, shaobo-he-aws requested changes

2024-09-18 19:18 UTC, shaobo-he-aws commented on cedar-policy-core/src/ast/entity.rs
> +    /// The implementation of [`Eq`] and [`PartialEq`] for
Can you add the feature flag to core as well?

2024-09-18 19:23 UTC, shaobo-he-aws commented on cedar-policy-core/src/ast/entity.rs
> +    /// The implementation of [`Eq`] and [`PartialEq`] for
Or generally, do you need changes to core at all? It seems you can put everything into the validator.

2024-09-27 18:22 UTC, shaobo-he-aws commented
Closed in favor of a single PR.

2024-09-27 18:22 UTC, closed without merging