new bugfix for 3.2.x
cedar-policy/cedar pull request #1110
Opened 2024-08-02 20:00 UTC by aaronjeline

## Description of changes
Pulls in #1004 and bump version 3.2.4
## Issue #, if available

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [X] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

2024-08-02 20:52 UTC, cdisselkoen approved these changes

2024-08-03 16:40 UTC, shaobo-he-aws approved these changes

2024-08-05 12:43 UTC, khieta requested changes
Looks like this PR only includes #1004, but not #943?

2024-08-05 14:40 UTC, khieta approved these changes

2024-08-05 14:41 UTC, merged