make public partial evaluation API experimental
cedar-policy/cedar pull request #178
Opened 2023-07-13 23:25 UTC by andrewmwells-amazon

make public partial evaluation API experimental

## Issue #, if available

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [ ] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).
- [ ] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).
- [ x] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [ ] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)
- [ ] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [ x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).
- [ ] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [ x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.
- [ ] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)
- [ ] Requires updates, but I do not plan to make them in the near future. (Make sure that your changes are hidden behind a feature flag to mark them as experimental.)
- [ ] I'm not sure how my change impacts `cedar-spec`. (Post your PR anyways, and we'll discuss in the comments.)

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-13 23:27 UTC, shaobo-he-aws approved these changes
LGTM.

2023-07-14 12:54 UTC, cdisselkoen requested changes
I feel like we should do slightly more in this PR. 
- move `Entities::partial()` behind this flag
- move `PartialResponse` behind this flag
- move `ResidualResponse` behind this flag

2023-07-14 12:54 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    #[cfg(feature = "partial_eval")]
Typically this annotation would go below the `///` docs, not above them

2023-07-14 20:31 UTC, andrewmwells-amazon commented
I think we want to make sure the build with / without `--features "experimental"` has no warnings? That's what I've done in the latest commit. The downside is it requires `#[allow(unused)]` annotations we may then forget to remove if/when the feature is no longer experimental. I added comments naming the feature to each usage; maybe that's good enough.

2023-07-14 20:41 UTC, cdisselkoen commented on cedar-policy/Cargo.toml
> +experimental = ["partial-eval"]
Is the intent that `experimental` would turn on all experimental features?  If so can we have a comment documenting that?

2023-07-14 20:42 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    #[allow(unused)] //Feature: partial-eval
This could be `#[cfg_attr(feature = "partial-eval", allow(unused))]`

Likewise elsewhere

2023-07-14 21:12 UTC, andrewmwells-amazon commented
> * move `PartialResponse` behind this flag

Hmm, this change will be more invasive. Specifically it would require rewriting `is_authorized_core(`.

2023-07-14 21:13 UTC, andrewmwells-amazon commented
> I feel like we should do slightly more in this PR.
> 
> * move `Entities::partial()` behind this flag
> * move `ResidualResponse` behind this flag

Did these two.

2023-07-14 21:13 UTC, andrewmwells-amazon commented
> I think we want to make sure the build with / without `--features "experimental"` has no warnings? That's what I've done in the latest commit. The downside is it requires `#[allow(unused)]` annotations we may then forget to remove if/when the feature is no longer experimental. I added comments naming the feature to each usage; maybe that's good enough.

`#[cfg_attr(not(feature = "partial-eval"), allow(unused))]` works instead

2023-07-14 22:04 UTC, shaobo-he-aws approved these changes

2023-07-17 17:03 UTC, cdisselkoen approved these changes

2023-07-17 17:03 UTC, cdisselkoen commented on cedar-policy/src/api.rs
>  mod test {
could we maybe rename the `test` module to be clear it's only tests related to partial evaluation?  Doesn't have to block this PR though

2023-07-17 19:18 UTC, andrewmwells-amazon commented
>Hmm, this change will be more invasive. Specifically it would require rewriting `is_authorized_core(`

Did the more granular change I think Craig intended instead of the more invasive change of hiding just the `Residual(ResidualResponse)` variant.

2023-07-17 20:20 UTC, aaronjeline approved these changes

2023-07-17 21:19 UTC, merged