New semantics for equality on IP ranges
cedar-policy/cedar pull request #348
Opened 2023-10-06 21:04 UTC by cdisselkoen

## Description of changes

Changes the semantics of equality on IP ranges.  For example, `ip("192.168.0.1/24") == ip("192.168.0.3/24")` was previously `true` and is now `false`.

Does not affect equality of single IP addresses, and does not change the behavior of `.isInRange()` at all.

Includes a lot more tests for edge-cases of IP semantics, including many tests for equality with the same or different subnets, equality between a single address and a range, and `.isInRange()` on a wider variety of edge cases.

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)

I may not make these updates myself, but I'm in contact with Cedar maintainers who are preparing to make these changes.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-06 21:14 UTC, shaobo-he-aws commented on cedar-policy-core/src/extensions/ipaddr.rs
> +    /// the actual address, without subnet
Should we rename this struct to `IpNet`?

2023-10-06 21:15 UTC, shaobo-he-aws commented on cedar-policy-core/src/extensions/ipaddr.rs
> +        str.as_ref().parse()
Do we need this function? Why not just use the implementation of `FromStr`?

2023-10-06 21:19 UTC, shaobo-he-aws commented on cedar-policy-core/src/extensions/ipaddr.rs
> +        self.addr.is_multicast() && self.subnet >= if self.is_ipv4() { 4 } else { 8 }
Should `>=` here be just `==`?

2023-10-06 21:30 UTC, emina approved these changes

2023-10-06 22:29 UTC, andrewmwells-amazon approved these changes

2023-10-07 00:26 UTC, andrewmwells-amazon requested changes
I think we should more seriously consider splitting networks and addresses into different types.

2023-10-07 01:06 UTC, emina commented
Splitting networks and addresses would be an invasive breaking change.  We’d break the schema of every user of the IP extension, because they’d have to change their IP attribute types to differentiate between addresses and ranges.

2023-10-10 19:15 UTC, aaronjeline approved these changes

2023-10-16 21:21 UTC, andrewmwells-amazon approved these changes

2023-10-16 21:27 UTC, shaobo-he-aws approved these changes

2023-10-16 21:27 UTC, andrewmwells-amazon approved these changes

2023-10-16 21:37 UTC, mwhicks1 approved these changes

2023-10-17 15:23 UTC, aaronjeline approved these changes

2023-10-17 15:27 UTC, merged