Run `confusable_string_checker` in `Validator::validate`
cedar-policy/cedar pull request #404
Opened 2023-11-06 16:08 UTC by john-h-kastner-aws

## Description of changes

Adds `ValidationWarning`s to the `ValidationResult` struct, and fixes #226 by including confusable string checking in validation as a warning. I don't consider this fully resolving #225 because there are still substantial changes required inside the validator to support warnings returned by the typechecker.

## Checklist for requesting a review
               
The change in this PR is (choose one, and delete the other options):

- [ ] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).
- [x] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).
- [ ] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [ ] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)
- [ ] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).
- [ ] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.
- [ ] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)
- [ ] Requires updates, but I do not plan to make them in the near future. (Make sure that your changes are hidden behind a feature flag to mark them as experimental.)
- [ ] I'm not sure how my change impacts `cedar-spec`. (Post your PR anyways, and we'll discuss in the comments.)

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-06 16:13 UTC, aaronjeline requested changes

2023-11-06 16:13 UTC, aaronjeline commented on cedar-policy-validator/src/validation_result.rs
>  impl<'a> ValidationResult<'a> {
Do we want an easy method for "validation passed and there were no warnings"?

2023-11-06 18:00 UTC, andrewmwells-amazon approved these changes

2023-11-08 16:35 UTC, aaronjeline approved these changes

2023-11-08 16:35 UTC, merged