Revert breaking schema change on v2.4.x
cedar-policy/cedar pull request #520
Opened 2023-12-19 20:20 UTC by john-h-kastner-aws

## Description of changes

Reverts schema parsing change from #132 and related PRs that resulted in a breaking change to schema parsing released in v2.3.2. I've chosen to revert the changes instead of applying an isolated fix for the compatibility issue because I feel this is less likely to leave any outstanding compatibility issues, and reverted change is already available in and will not be reverted in v3.0.0. 

For confidence that after this change schema parsing will not change between 2.3.0 and 2.4.x:

* [Small `schema_file_format.rs` diff](https://gist.github.com/john-h-kastner-aws/f3c1d270fc61079dd5e0ec6c338eed1a#file-schema_file_format-rs-diff)
* [Larger `schema.rs` diff](https://gist.github.com/john-h-kastner-aws/f3c1d270fc61079dd5e0ec6c338eed1a#file-schema-rs-diff) (not changed by this PR, but relevant to schema parsing) 

[full diff](https://github.com/cedar-policy/cedar/compare/v2.3.0...fix/jkastner/schema_break.revert)

## Issue #, if available

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-19 20:22 UTC, aaronjeline approved these changes

2023-12-19 20:24 UTC, aaronjeline requested changes
We're relying on some weird behaviour of serde here. We should pin the serde for this release

2023-12-19 20:40 UTC, aaronjeline approved these changes

2023-12-19 22:58 UTC, shaobo-he-aws approved these changes

2023-12-20 14:01 UTC, cdisselkoen approved these changes

2023-12-20 14:01 UTC, cdisselkoen commented on cedar-policy/CHANGELOG.md
> +  is missing a required key.
```suggestion
- Reverted accidental breaking change to schema format introduced in the 2.3.2 release.
  Attribute types in schema files may now contain unexpected keys (as they could before 2.3.2). 
  As a side effect, schema parsing error messages are less useful when an attribute type
  is missing a required key.
  The 2.4.2 behavior, including the more useful error messages, remain available in 3.0.0.
```

2023-12-20 20:19 UTC, cdisselkoen approved these changes

2023-12-20 20:21 UTC, merged