docs: enable crate all features and rust doc_auto_cfg feature while building docs for docs.rs
cedar-policy/cedar pull request #608
Opened 2024-01-29 09:49 UTC by iamsauravsharma

## Description of changes
Enable all features and [doc_auto_cfg](https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg) using docs.rs [metadata](https://docs.rs/about/metadata)

## Issue #, if available
Closes #607

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)

I confirm that this PR (choose one, and delete the other options):

- [X] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-30 15:04 UTC, aaronjeline commented
This is great thanks!
Two qs:
1) Do you know if it's possible to add some warning text to the documentation that's gated behind a feature? Those are "experimental" features and A) might not be correct and B) don't have the same stability guarantees and I don't want people to sleepwalk into that
2) You give a command above for building the documentation, do we need to configure that on crates.io at all?

2024-01-30 15:47 UTC, iamsauravsharma commented
1. Yes it is possible to add a warning to rust docs using https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#adding-a-warning-block which will look like [this example](https://rustdoc.crud.net/imperio/warning-block/foo/struct.Foo.html). Can you provide some warning text to be used? There will be also a feature banner to inform users it is gated behind the feature flag
2. No, It is not needed docs.rs will automatically read Cargo.toml `[package.metadata.docs.rs]` and run the same command while building docs. Above command is to check docs locally

2024-01-30 16:24 UTC, aaronjeline commented
How's this:
> This feature is experimental. For more information see https://github.com/cedar-policy/rfcs/blob/main/README.md#experimental-features

2024-01-31 03:51 UTC, iamsauravsharma commented
PR is updated with warning text. Now it will look like this
For struct
![Screenshot 2024-01-31 at 09-32-07 RequestBuilder in cedar_policy - Rust](https://github.com/cedar-policy/cedar/assets/38726015/a7aa2074-5107-4f26-9839-4a10ee496928)
and for function
![Screenshot 2024-01-31 at 09-31-51 Authorizer in cedar_policy - Rust](https://github.com/cedar-policy/cedar/assets/38726015/44ba40a6-56ff-49ff-87b0-12b2d1c95d68)

2024-01-31 14:49 UTC, aaronjeline commented
> PR is updated with warning text. Now it will look like this 
That looks great, thanks!

Bummer we need to manually specify it for each function/struct, but looks good to me

2024-01-31 14:57 UTC, aaronjeline requested changes
Only thing you missed is the partial-eval gated functions in `src/frontend/is_authorized` (which again go to a want for a more automated solution, but this is a great start!)

2024-01-31 15:07 UTC, aaronjeline approved these changes

2024-01-31 15:11 UTC, iamsauravsharma commented
There was some issue with include_str I have fixed it.

2024-01-31 18:43 UTC, shaobo-he-aws approved these changes

2024-02-05 18:56 UTC, aaronjeline approved these changes

2024-02-05 18:57 UTC, merged