allow `check-parse` command to read from stdin
cedar-policy/cedar pull request #70
Opened 2023-05-25 00:36 UTC by shaobo-he-aws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-25 13:02 UTC, aaronjeline approved these changes

2023-05-25 15:56 UTC, andrewmwells-amazon requested changes

2023-05-25 15:56 UTC, andrewmwells-amazon commented on cedar-policy-cli/src/lib.rs
> +fn read_from_file_or_stdin(filename: Option<impl AsRef<Path>>, context: &str) -> Result<String> {
Can we add some docs so users can hover over `read_from_file_or_stdin` and `read_from_file` and see why one would be used vs the other? Personally I find it confusing that `read_from_file` calls `read_from_file_or_stdin`

2023-05-25 21:16 UTC, andrewmwells-amazon approved these changes

2023-05-25 21:19 UTC, merged

2023-06-02 16:14 UTC, cdisselkoen commented on cedar-policy-cli/src/lib.rs
> +    pub policies_file: Option<String>,
A comment about what `None` implies would be helpful here.  (The comment gets incorporated into the `--help` by `clap`)