ESTs for policy sets
cedar-policy/cedar pull request #783
Opened 2024-04-11 14:54 UTC by aaronjeline

## Description of changes
Adds and EST for policy sets
(Also removes the `deserialize/serialize` impls from core policy sets, as far as I can tell no one is using them and it's a confusing duplicate)
## Issue #, if available
#549 
## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [X] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).

I confirm that this PR (choose one, and delete the other options):

- [ ] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [X] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

2024-04-11 15:27 UTC, aaronjeline commented
Semver check is failing because `serde_json::Error` doesn't implement `UnwindSafe`, causing `PolicySetError` to no longer implement `UnwindSafe`. Not clear how much we care about this, should we:
A) Don't care, keep the rich error type
B) Convert `serde_json::Error` to a string, preserving the `UnwindSafe`

2024-04-11 15:42 UTC, aaronjeline commented
> Semver check is failing because `serde_json::Error` doesn't implement `UnwindSafe`, causing `PolicySetError` to no longer implement `UnwindSafe`. Not clear how much we care about this, should we: A) Don't care, keep the rich error type B) Convert `serde_json::Error` to a string, preserving the `UnwindSafe`

I think we're fine with this break

2024-04-15 16:41 UTC, andrewmwells-amazon requested changes

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy-core/src/entities/json/value.rs
> +/// This is useful when for plumbing reasons, we can't get the appopriate values into the dynamic
```suggestion
/// This is useful when, for plumbing reasons, we can't get the appopriate values into the dynamic
```

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy-core/src/est/err.rs
> +    /// Error reported when attempting to create an invalid template-link
```suggestion
    /// Error reported when attempting to create a template-link
```

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy-core/src/est/err.rs
> +    /// Error reported when attempting to create an invalid template-link
Presumably they were attempting to create a valid template-link 😄

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy/src/api.rs
> +/// The first invocation of `f` that fails causes the whole computation fails
```suggestion
/// The first invocation of `f` that fails causes the whole computation to fail
```

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy/src/api.rs
> +fn parition_policies(
I don't like the name `partition`. Maybe something like `is_static_or_link`?

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy/src/api.rs
> +fn fold_parition<T, A, B, E>(
```suggestion
fn fold_partition<T, A, B, E>(
```

2024-04-15 16:41 UTC, andrewmwells-amazon commented on cedar-policy/src/api.rs
> +fn fold_parition<T, A, B, E>(
And the same throughout

2024-04-15 20:33 UTC, shaobo-he-aws approved these changes

2024-04-15 20:35 UTC, shaobo-he-aws commented
LGTM. I think we will also need to update the docs because policy links now have EST representations.

2024-04-16 13:05 UTC, cdisselkoen requested changes
Some of these more urgent than others.  Bunch of these are just comments/questions why things are a certain way

2024-04-16 13:05 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    #[error("Error serialzing a policy to the EST format: {0}")]
```suggestion
    #[error("Error serializing a policy to the EST format: {0}")]
```

2024-04-16 13:05 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    }
I think in other places we have the full trifecta of json constructors -- from value, str, and Read

2024-04-16 13:05 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +        .collect();
nit: we only need `env` in the `Some(template_id)` case, so we can move this computation into that branch

2024-04-16 13:05 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +/// Like [`itertools::Itertools::partion_map`], but accepts a function that can fail.
```suggestion
/// Like [`itertools::Itertools::partition_map`], but accepts a function that can fail.
```

2024-04-16 13:05 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    fn test_parition_fold() {
```suggestion
    fn test_partition_fold() {
```

and elsewhere below

2024-04-17 20:30 UTC, aaronjeline commented on cedar-policy-core/src/entities/json/value.rs
>      },
Had to go in one of the cases, just picked one

2024-04-17 20:30 UTC, aaronjeline commented on cedar-policy-core/src/entities/json/value.rs
> +        let ctx = || C::static_context().unwrap_or_else(&dynamic_ctx);
Dynamic context will always be present, (at least with the current type signature)

2024-04-17 20:36 UTC, aaronjeline commented on cedar-policy-core/src/entities/json/value.rs
> +}
It's unclear to me how you'd thread that argument through though

2024-04-17 23:26 UTC, shaobo-he-aws approved these changes

2024-04-18 12:35 UTC, cdisselkoen commented on cedar-policy-core/src/entities/json/value.rs
> +}
You're probably right, I was just musing

2024-04-19 19:35 UTC, john-h-kastner-aws commented on cedar-policy-core/src/entities/json/value.rs
> +        let ctx = || C::static_context().unwrap_or_else(&dynamic_ctx);
If we always have a dynamic context, what's the purpose of a static context?

2024-04-19 19:39 UTC, aaronjeline commented on cedar-policy-core/src/entities/json/value.rs
> +        let ctx = || C::static_context().unwrap_or_else(&dynamic_ctx);
Sometimes the dynamic context can't be set correct (for example in FromStr impls) so we need to get the correct context in there

2024-04-19 19:44 UTC, cdisselkoen approved these changes

2024-04-19 19:44 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    /// Error when covnerting to EST
```suggestion
    /// Error when converting to EST
```

2024-04-22 13:36 UTC, aaronjeline commented on cedar-policy-core/src/est/policy_set.rs
> +    pub env: HashMap<SlotId, EntityUID>,
Yeah I agree

2024-04-22 13:55 UTC, cdisselkoen approved these changes

2024-04-22 13:55 UTC, cdisselkoen commented on cedar-policy/CHANGELOG.md
> +- Adds an EST representation for Policy Sets (#783, resolving #549)
nit: maybe list the specific methods being added.  People don't necessarily know what "EST" is, that is internal terminology

2024-04-22 13:55 UTC, cdisselkoen commented on cedar-policy/src/api.rs
> +    ToEST(#[from] PolicyToJsonError),
Similarly here we can avoid using the "EST" internal terminology and just say `FromJson` and "Error deserializing a JSON policy/template" and "Error serializing a policy to the JSON format" etc

2024-04-23 13:45 UTC, merged